name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Version in TOC and LUA
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/## Version: .*/## Version: $VERSION/" SausageThreat.toc
          sed -i "s/local SAUSAGE_VERSION = \".*\"/local SAUSAGE_VERSION = \"v$VERSION\"/" SausageThreat.lua

      - name: Create Zip
        run: |
          mkdir SausageThreat
          cp SausageThreat.lua SausageThreat.toc SausageThreat
          cp -r sound SausageThreat/
          cp -r Textures SausageThreat/
          zip -r SausageThreat.zip SausageThreat

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: SausageThreat.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
